[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
fs_permissions = [
  { access = "read-write", path = "./addresses.json" },
  { access = "read-write", path = "./out" },
  { access = "read", path = "../chainlink/openai" },
]

[rpc_endpoints]
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

optimism-sepolia = "https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

anvil = "http://127.0.0.1:8545"

[etherscan]
optimism = {key = "${ETHERSCAN_API_KEY_OPTIMISM}"}
base = {key = "${ETHERSCAN_API_KEY_BASE}"}

optimism-sepolia = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY_BASE}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
